<a href="https://colab.research.google.com/github/srinivaspoola007/Data-Science/blob/main/Narray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy **Array**

In [ ]:
import numpy as np


list is converted to an array

In [ ]:
my_lst=[[3,4,5],[7,8,9],[1,2,3]]
np.array(my_lst)

array([[3, 4, 5],
       [7, 8, 9],
       [1, 2, 3]])

ranging the array

In [ ]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

ranging with step size

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

zeros array of 3rows and 4 columns

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

linspace take points we want

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

this generates the identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5) #gives a 1D array 0-1 of 5 elements

array([0.47392722, 0.59988953, 0.83716627, 0.08752112, 0.58071566])

In [ ]:
np.random.randn(5,5) #gives a 2D array

array([[-0.06204091, -0.26917167,  0.05343716,  1.01447645,  1.16404832],
       [-0.82366508, -0.55839152,  1.21213678, -0.10834446,  1.49206301],
       [ 1.02210799,  1.23374482, -0.65867217,  0.43207621,  1.67774349],
       [-0.21193434, -0.74643686,  0.03184973,  1.20138464, -0.04433853],
       [ 0.23824284,  0.07008778, -0.14774806,  0.12718575,  0.0874463 ]])

In [ ]:
naarrr=np.random.randint(1,100,10)
naarrr

array([57, 85, 58, 18, 40, 27, 33,  3, 36, 62])

In [ ]:
naarrr.size

10

In [ ]:
naarrr.reshape((5,2))

array([[57, 85],
       [58, 18],
       [40, 27],
       [33,  3],
       [36, 62]])

## numpy indexing and **selection**

for 1 D array

In [ ]:
arry=np.arange(0,15)
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arry[9]

9

In [ ]:
arry[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arry[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arry[5:]=100
arry

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [ ]:
arry=np.arange(0,15)
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

for 2D array

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

to grab any use indexing for exmple to select 5

In [ ]:
arr_2d[1,1]

5

In [ ]:
arr_2d[:1,2:]

array([[3]])

give the results ACCORDING TO CONDITION

In [ ]:
arr_2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
arr_2d[arr_2d > 5]

array([6, 7, 8, 9])